package es_mapping

const Product = `{
  "madara_test":{
    "aliases":{},
    "mappings":{
      "madara":{
        "dynamic_templates":[
          {
            "string_template":{
              "match":"*",
              "match_mapping_type":"string",
              "mapping":{ "fields":null,"index":false,"type":"text"}
            }
          }
        ],
        "properties":{
          "store_id":{"type":"long"},
          "title":{"type":"text","fields":{"analyzed":{"type":"text","analyzer":"searchkick_index"},"word_start":{"type":"text","analyzer":"searchkick_word_start_index"}}},
          "published":{"type":"boolean"},
          "updated_at":{"type":"long"},
          "created_at":{"type":"long"},
        }
      }
    },
    "settings":{
      "index":{
        "max_ngram_diff":"49",
        "number_of_shards":"1",
        "provided_name":"madara_test",
        "max_shingle_diff":"4",
        "max_result_window":"100000",
        "creation_date":"1617096384254",
        "analysis":{
          "filter":{
            "searchkick_suggest_shingle":{"max_shingle_size":"5","type":"shingle"},
            "searchkick_edge_ngram":{"type":"edge_ngram","min_gram":"1","max_gram":"50"},
            "searchkick_index_shingle":{"token_separator":"","type":"shingle"},
            "searchkick_search_shingle":{"token_separator":"","output_unigrams_if_no_shingles":"true","output_unigrams":"false","type":"shingle"},
            "my_stop_filter":{"type":"stop","stopwords":"_english_"},
            "searchkick_ngram":{"type":"ngram","min_gram":"1","max_gram":"50"}
          },
          "analyzer":{
            "searchkick_word_start_index":{
              "filter":["lowercase","asciifolding","searchkick_edge_ngram"],
              "type":"custom","tokenizer":"standard"
            },
            "searchkick_keyword":{
              "filter":["lowercase"],
              "type":"custom",
              "tokenizer":"keyword"
            },
            "searchkick_text_end_index":{
              "filter":["lowercase","asciifolding","reverse","searchkick_edge_ngram","reverse"],
              "type":"custom",
              "tokenizer":"keyword"
            },
            "searchkick_search2":{
              "filter":["lowercase","asciifolding"],
              "char_filter":["ampersand"],
              "type":"custom",
              "tokenizer":"standard"
            },
            "searchkick_word_middle_index":{
              "filter":["lowercase","asciifolding","searchkick_ngram"],
              "type":"custom","tokenizer":"standard"
            },
            "searchkick_search":{
              "filter":["lowercase","asciifolding","searchkick_search_shingle"],
              "char_filter":["ampersand"],
              "type":"custom",
              "tokenizer":"standard"
            },
            "searchkick_text_start_index":{
              "filter":["lowercase","asciifolding","searchkick_edge_ngram"],
              "type":"custom",
              "tokenizer":"keyword"
            },
            "searchkick_word_end_index":{
              "filter":["lowercase","asciifolding","reverse","searchkick_edge_ngram","reverse"],
              "type":"custom",
              "tokenizer":"standard"
            },
            "searchkick_word_search":{
              "filter":["lowercase","asciifolding"],
              "type":"custom",
              "tokenizer":"standard"
            },
            "searchkick_autocomplete_search":{
              "filter":["lowercase","asciifolding"],
              "type":"custom","tokenizer":"keyword"
            },
            "searchkick_suggest_index":{
              "filter":["lowercase","asciifolding","searchkick_suggest_shingle"],
              "type":"custom","tokenizer":"standard"
            },
            "searchkick_text_middle_index":{
              "filter":["lowercase","asciifolding","searchkick_ngram"],"type":"custom","tokenizer":"keyword"
            },
            "icu_analyzer":{
              "filter":["icu_normalizer","lowercase","asciifolding","searchkick_index_shingle","my_stop_filter"],
              "char_filter":["icu_normalizer","ampersand"],"type":"custom","tokenizer":"icu_tokenizer"
            },
            "searchkick_index":{
              "filter":["lowercase","asciifolding","searchkick_index_shingle"],
              "char_filter":["ampersand"],"type":"custom","tokenizer":"standard"
            }
          },
          "char_filter":{
            "ampersand":{"type":"mapping","mappings":["&=> and "]}
          }
        },
        "number_of_replicas":"0",
        "uuid":"RD8AWz-0QB6fSqAqLmQg0w",
        "version":{"created":"6070099"}
      }
    }
  }
}`
